server:
    ssl:
        key-store: classpath:server.p12
        key-store-password: mypassword
        key-store-type: PKCS12
        key-alias: tomcat
    port: 8443
security:
  oauth2:
    client:
      clientId: '@!6966.2ADD.37AF.44CA!0001!9AF2.DF30!0008!72EA.0B87.0065.E5C9'
      clientSecret: 4537f68e-6775-4c11-b963-b5b154ac67cc
      accessTokenUri: https://gluu.localhost.info/oxauth/seam/resource/restv1/oxauth/token
      userAuthorizationUri: https://gluu.localhost.info/oxauth/seam/resource/restv1/oxauth/authorize
      tokenName: access_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: openid, profile
    resource:
      userInfoUri: https://gluu.localhost.info/oxauth/seam/resource/restv1/oxauth/userinfo

logging:
  level:
    org.springframework.security: DEBUG
